name: Test make documentation

on:
  push:
    branches:
      - master
      - '[34].[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[34].[0-9]+.x'

jobs:
  build-dev-docs:
    name: 'Build development docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install sphinxcontrib-phpdomain
          pip install sphinx-multiversion
          pip install git+https://github.com/marc1706/sphinx-php.git
      - name: Test make html
        run: |
          cd development
          make html

  build-user-docs-pdf:
    name: 'Build user docs PDF'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install fop
        run: |
          sudo apt-get install -y fop
      - name: Build pdf documentation
        working-directory: ${{ github.workspace }}/documentation
        run: |
          ./create_pdf.sh
      - name: Archive PDF output
        uses: actions/upload-artifact@v4
        with:
          name: Documentation PDF
          path: ${{ github.workspace }}/documentation/*.pdf
